import Navbar from './components/navbar'
import Footer from './components/footer'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Pizzon',
  description: 'Generated by Chelsofia',
  keywords: 'pizza, pizzon, best pizza',
  description: 'Find the best pizza',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}> 
        <Navbar/>
        {children}
        <Footer/>
         </body>
    </html>
  )
}






